services:
  postgres:
    container_name: postgres
    image: postgres:15.3-alpine3.18
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    networks:
      - app-network
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - app
    networks:
      - app-network
  grafana:
    container_name: grafana
    image: grafana/grafana
    env_file:
      - docker/grafana/grafana.env
    volumes:
      - ./docker/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./docker/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./docker/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    networks:
      - app-network
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - postgres
networks:
  app-network:
    driver: bridge